### ISSUE TITLE
Not found (404)

### ISSUE THREAD

**Issue by neelakshthakur-eng** [catherinedeguia/Teamified-Graphic-Design-Web-Dev#86]
Not found (404)

**Comment by neelakshthakur-eng** [comment]
https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.teamified.com%2F&item_key=CAMYDSAC

**Comment by neelakshthakur-eng** [comment]
We’ve identified several pages currently returning 404 (Not Found). To avoid a poor user experience and loss of SEO value, I recommend setting up 301 redirects from the old URLs to their best live equivalents.
This will:
Ensure visitors are guided to working pages
 Preserve SEO authority by passing ranking signals
Resolve errors in Google Search Console and improve site health

Proposed redirect mappings (examples):

/about-us-old → /about
/get-a-role → /careers
/old-home-3 → / (homepage)
Could you please confirm these mappings or provide me with the final destination URLs for all. I can proceed with setting up the redirects in Webflow and then validate the fix in Google Search Console?




<img width="1376" height="740" alt="Image" src="https://github.com/user-attachments/assets/c97fda1e-765c-4f06-93b6-541c6d863806" />
Confirm Following:
OLD                                         NEW
1. /about-us-old                      /about
2. /build-your-team                /build-your-team
3. /services                            /services
4. /old-home-3                      /
5. /get-a-role                         /careers
6. /guides                               /resources
7. /hire-contractors              /build-your-team
8. /hire-fractional-roles       /build-your-team
9. /employer-of-record         /services
10. /partnerships                   /about

**Comment by neelakshthakur-eng** [comment]
@catherinedeguia  https://docs.google.com/spreadsheets/d/1-qgWO2H99ZOYX_XnhF2F-Gb9Ib1Tf5gLps6Md_f5PXo/edit?usp=sharing 
We can redirect these old urls to new one can you please provide me the new ? or ensure these are the right one

**Comment by catherinedeguia** [comment]
Hello @neelakshthakur-eng ! Can you please give me edit access so I can add the links on the file? :) Thanks!

**Comment by neelakshthakur-eng** [comment]
Done @catherinedeguia

**Comment by catherinedeguia** [comment]
@neelakshthakur-eng Added the links :)

for context we already have a Build your Team page but it is still not yet live because ms darlyn wanted to change the look of the page once we have our UX/UI designer

**Comment by neelakshthakur-eng** [comment]
All old URLs listed in **YELLOW** have been redirected to their respective new URLs via 301 redirects. This ensures that visitors landing on outdated links are guided to the correct live pages, preserving SEO value and eliminating 404 errors. Validation will now be run in Google Search Console to confirm fixes.
@catherinedeguia 
FYI @darlyndayag-jpg
